-- =========================================================================
-- seed.sql
-- Runs automatically after `supabase db reset` (local dev only — never
-- run against UAT or production). Use this for throwaway sample data to
-- develop against locally.
--
-- Reference/master data that MUST exist in every environment (permissions,
-- notification types, retention policies, consent notice, vehicle catalogue,
-- pricing rules, invoice series, …) is seeded by migrations, not here —
-- migrations are what runs in UAT/production; this file is not.
--
-- Intentionally empty: the previous contents targeted the old schema
-- (plans.billing_cycle, stations) and would fail against this one.
-- =========================================================================
